name: Health Check

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

concurrency:
  group: healthy-update
  cancel-in-progress: true

jobs:
  check-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ⬇️ مرحله‌ی تست شما باید فایل خروجی سالم‌ها را بسازد
      # اگر از قبل مرحله دارید، فقط مطمئن شو خروجی‌اش به NEW_RESULTS_FILE می‌رود
      - name: Run health tests
        env:
          NEW_RESULTS_FILE: artifacts/healthy_new.txt
        run: |
          mkdir -p artifacts
          # TODO: به‌جای خط‌های نمونه، اسکریپت تست واقعی‌تان را قرار دهید که لینک‌های سالم ایران را خروجی دهد
          # python3 scripts/your_health_check.py --out "$NEW_RESULTS_FILE"
          echo " " > "$NEW_RESULTS_FILE"  # placeholder: حذف و با خروجی واقعی جایگزین شود

      - name: Ensure merge script exists
        run: |
          test -f scripts/merge_healthy.py || (echo "merge_healthy.py missing" && exit 1)
          python3 -c "import sys; print('python ok')"

      - name: Merge Healthy.txt (append + dedup)
        env:
          NEW_RESULTS_FILE: artifacts/healthy_new.txt
        run: |
          mkdir -p configs
          python3 scripts/merge_healthy.py "$NEW_RESULTS_FILE" "configs/Healthy.txt"

      - name: Commit & Push
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git add configs/Healthy.txt
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git pull --rebase origin "$BRANCH_NAME" || true
          git commit -m "chore: merge healthy configs (append + dedup)"
          git push origin HEAD:"$BRANCH_NAME"
